# Ship a minimal metadata file that can be picked up by Streamlit at runtime.
[project]
name = "chessboard_component"
version = "0.0.1"

[[tool.streamlit.component.components]]
name = "chessboard_component"
asset_dir = "frontend/build"
