name: Initialize Player Database

on:
  workflow_dispatch: # Isso cria o botão "Run workflow"

jobs:
  fix-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Instalamos dependências caso o script use algo externo (mesmo que use só padrão, é seguro)
      - name: Install dependencies
        run: pip install requests pandas ndjson

      - name: Run History Fix Script
        run: python scripts_cron/fix_history.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: Rebuild player database from local history"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
