name: Teste Hugging Faces

on:
  workflow_dispatch: # Botão "Run workflow"

jobs:
  build-positions:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-chess pyarrow duckdb huggingface_hub

      # 4. Executa o script
      - name: Build and upload positions to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scriptscron/games_to_hugging_faces.py
